name: '🐞 Bug report'
description: Reporte um problema encontrado na Shared UI
labels: ['type: bug']
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar! Evite inserir dados pessoais reais.
  - type: input
    id: summary
    attributes:
      label: Resumo
      description: Descreva brevemente o bug
      placeholder: Ex. Componente Button não aplica variante corretamente
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: Liste os passos
      placeholder: |
        1. Importar o componente Button
        2. Definir variant="secondary"
        3. Renderizar o componente
        4. Verificar estilos aplicados
      render: bash
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportamento esperado
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Comportamento atual
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Área afetada
      options:
        - Componentes UI
        - Tema/Estilos
        - Types/TypeScript
        - Storybook/Docs
        - Build/Vite
        - Exports/Index
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs/erros
      description: Cole trechos relevantes (sem dados sensíveis)
      render: bash
  - type: input
    id: version
    attributes:
      label: Versão/commit
      placeholder: Ex. 0.1.5 / abcdef1
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: Não inclui dados pessoais reais
          required: true
        - label: Verifiquei se ocorre em `develop` mais recente
          required: true
