name: '❓ Dúvida'
description: Abra uma pergunta técnica geral
labels: ['type: question']
body:
  - type: input
    id: topic
    attributes:
      label: Tópico
      placeholder: Ex. Como customizar tema / Integração com MUI
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Pergunta
      description: Descreva a dúvida objetivamente
      placeholder: |
        Como implementar um componente customizado usando o tema GovBR?
