name: "🔐 Vulnerabilidade (privado)"
description: Para reportes de segurança, siga SECURITY.md (não abra issue pública com detalhes)
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Não** descreva detalhes sensíveis aqui.
        Siga o fluxo do arquivo SECURITY.md (e-mail/Private Vulnerability Reporting).
  - type: input
    id: contact
    attributes:
      label: E-mail de contato
      placeholder: seu@dominio.tld
